//
//  GBZBubbleView.m
//  Mechanimals
//
//  Created by Federico Guardabrazo Vallejo on 24/07/14.
//  Copyright (c) 2014 guardabrazo. All rights reserved.
//

#import "GBZBubbleView.h"

@implementation GBZBubbleView

- (id)initWithFrame:(CGRect)frame
{
    self = [super initWithFrame:frame];
    if (self) {
        // Initialization code
        self.backgroundColor = [UIColor clearColor];
    }
    return self;
}


- (void)drawRect:(CGRect)rect{
    
    //// Color Declarations
    UIColor* color21 = [UIColor whiteColor];
    UIColor* color22 = [UIColor colorWithRed: 0.239 green: 0.239 blue: 0.239 alpha: 1];
    
    
    CGRect frame = rect;

    //// Bezier Drawing
    UIBezierPath* bezierPath = UIBezierPath.bezierPath;
    [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.75866 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74798 * CGRectGetHeight(frame))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.95916 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.95901 * CGRectGetHeight(frame))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.95916 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53024 * CGRectGetHeight(frame))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.95916 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.24530 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.75866 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.02755 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.95916 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.12504 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.86939 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.02755 * CGRectGetHeight(frame))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.23391 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.02755 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.03342 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.24530 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.12318 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.02755 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.03342 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.12504 * CGRectGetHeight(frame))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.03342 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53024 * CGRectGetHeight(frame))];
    [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.23391 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74798 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.03342 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.65050 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.12318 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74798 * CGRectGetHeight(frame))];
    [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.75866 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74798 * CGRectGetHeight(frame))];
    [bezierPath closePath];
    bezierPath.miterLimit = 4;
    
    [color21 setFill];
    [bezierPath fill];
    
    
    //// Bezier 2 Drawing
    UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
    [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.14025 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35225 * CGRectGetHeight(frame))];
    [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.19537 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44781 * CGRectGetHeight(frame))];
    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.18304 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45949 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.19383 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46216 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.18972 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46605 * CGRectGetHeight(frame))];
    [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.11995 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35225 * CGRectGetHeight(frame))];
    [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.14025 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35225 * CGRectGetHeight(frame))];
    [bezier2Path closePath];
    [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.17071 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36800 * CGRectGetHeight(frame))];
    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.18485 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35383 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.17184 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35899 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.17655 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35427 * CGRectGetHeight(frame))];
    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.19923 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36905 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.19363 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35462 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.19843 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35969 * CGRectGetHeight(frame))];
    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.18485 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38402 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.19730 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37833 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.19250 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38332 * CGRectGetHeight(frame))];
    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.17071 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36800 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.17639 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38279 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.17168 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37745 * CGRectGetHeight(frame))];
    [bezier2Path closePath];
    [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.26033 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32351 * CGRectGetHeight(frame))];
    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.24413 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.30054 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.25699 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31292 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.25159 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.30526 * CGRectGetHeight(frame))];
    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.22014 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.29909 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.23668 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.29581 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.22868 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.29533 * CGRectGetHeight(frame))];
    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.19996 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32285 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.21160 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.30286 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.20487 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31077 * CGRectGetHeight(frame))];
    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.19307 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37207 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.19504 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33493 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.19275 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35133 * CGRectGetHeight(frame))];
    [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.17567 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37220 * CGRectGetHeight(frame))];
    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.18382 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31583 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.17534 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34814 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.17806 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32935 * CGRectGetHeight(frame))];
    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.20594 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.28728 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.18958 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.30231 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.19696 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.29279 * CGRectGetHeight(frame))];
    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.23513 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.28052 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.21493 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.28177 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.22465 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.27952 * CGRectGetHeight(frame))];
    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.26196 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.29365 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.24560 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.28153 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.25455 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.28590 * CGRectGetHeight(frame))];
    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.27792 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32653 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.26937 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.30139 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.27469 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31235 * CGRectGetHeight(frame))];
    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.28275 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38310 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.28114 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34070 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.28275 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35956 * CGRectGetHeight(frame))];
    [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.23622 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38310 * CGRectGetHeight(frame))];
    [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.23622 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36696 * CGRectGetHeight(frame))];
    [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.26595 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36696 * CGRectGetHeight(frame))];
    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.26033 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32351 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.26554 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34858 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.26367 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33410 * CGRectGetHeight(frame))];
    [bezier2Path closePath];
    [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.25483 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36748 * CGRectGetHeight(frame))];
    [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.19295 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46002 * CGRectGetHeight(frame))];
    [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.18364 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44466 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.18441 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46553 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.18130 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46041 * CGRectGetHeight(frame))];
    [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.23646 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36722 * CGRectGetHeight(frame))];
    [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.25483 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36748 * CGRectGetHeight(frame))];
    [bezier2Path closePath];
    bezier2Path.miterLimit = 4;
    
    [color22 setFill];
    [bezier2Path fill];
    
    
    //// Bezier 3 Drawing
    UIBezierPath* bezier3Path = UIBezierPath.bezierPath;
    [bezier3Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.38778 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42313 * CGRectGetHeight(frame))];
    [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.43056 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41322 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.40655 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42340 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.42081 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42009 * CGRectGetHeight(frame))];
    [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.45709 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38756 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.44031 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.40635 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.44915 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39780 * CGRectGetHeight(frame))];
    [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.46900 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38165 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.46503 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37732 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.46900 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37535 * CGRectGetHeight(frame))];
    [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.43600 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42189 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.46037 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39890 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.44937 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41230 * CGRectGetHeight(frame))];
    [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.39068 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43783 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.42262 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43147 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.40752 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43678 * CGRectGetHeight(frame))];
    [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.35859 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43048 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.38141 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43827 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.37072 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43582 * CGRectGetHeight(frame))];
    [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.32807 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.40784 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.34646 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42515 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.33629 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41760 * CGRectGetHeight(frame))];
    [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.31490 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38428 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.31985 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39808 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.31546 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39023 * CGRectGetHeight(frame))];
    [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.32964 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39176 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.31619 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37816 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.32110 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38065 * CGRectGetHeight(frame))];
    [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.35641 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41598 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.33818 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.40288 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.34711 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41095 * CGRectGetHeight(frame))];
    [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.38778 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42313 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.36572 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42101 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.37617 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42340 * CGRectGetHeight(frame))];
    [bezier3Path closePath];
    [bezier3Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.39104 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.30434 * CGRectGetHeight(frame))];
    [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.39999 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.30861 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.39450 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.30434 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.39749 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.30577 * CGRectGetHeight(frame))];
    [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.40373 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31957 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.40248 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31145 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.40373 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31511 * CGRectGetHeight(frame))];
    [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.39999 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33033 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.40373 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32386 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.40248 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32744 * CGRectGetHeight(frame))];
    [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.39086 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33467 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.39749 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33322 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.39444 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33467 * CGRectGetHeight(frame))];
    [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.38186 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33040 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.38727 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33467 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.38427 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33324 * CGRectGetHeight(frame))];
    [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.37823 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31957 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.37944 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32756 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.37823 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32395 * CGRectGetHeight(frame))];
    [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.38246 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.30828 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.37823 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31484 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.37964 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31108 * CGRectGetHeight(frame))];
    [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.39104 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.30434 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.38488 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.30566 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.38774 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.30434 * CGRectGetHeight(frame))];
    [bezier3Path closePath];
    [bezier3Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.39696 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33204 * CGRectGetHeight(frame))];
    [bezier3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.39696 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39898 * CGRectGetHeight(frame))];
    [bezier3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.39696 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43272 * CGRectGetHeight(frame))];
    [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.39690 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46809 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.39720 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45328 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.39718 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46507 * CGRectGetHeight(frame))];
    [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.39527 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47432 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.39662 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47111 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.39608 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47319 * CGRectGetHeight(frame))];
    [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.39104 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47603 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.39447 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47546 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.39305 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47603 * CGRectGetHeight(frame))];
    [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.38681 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47400 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.38903 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47603 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.38762 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47535 * CGRectGetHeight(frame))];
    [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.38530 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46901 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.38600 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47264 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.38550 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47098 * CGRectGetHeight(frame))];
    [bezier3Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.38500 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45739 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.38510 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46704 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.38500 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46317 * CGRectGetHeight(frame))];
    [bezier3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.38500 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42602 * CGRectGetHeight(frame))];
    [bezier3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.38500 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39321 * CGRectGetHeight(frame))];
    [bezier3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.38500 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33230 * CGRectGetHeight(frame))];
    [bezier3Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.39696 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33204 * CGRectGetHeight(frame))];
    [bezier3Path closePath];
    bezier3Path.miterLimit = 4;
    
    [color22 setFill];
    [bezier3Path fill];
    
    
    //// Bezier 4 Drawing
    UIBezierPath* bezier4Path = UIBezierPath.bezierPath;
    [bezier4Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.57995 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.29594 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.63391 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32003 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.60074 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.29594 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.61872 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.30397 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.65670 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38060 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.64910 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33609 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.65670 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35628 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.63367 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44230 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.65670 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.40537 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.64902 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42593 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.57801 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46684 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.61832 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45866 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.59977 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46684 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.52447 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44400 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.55610 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46605 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.53825 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45844 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.49776 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37562 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.50683 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42405 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.49792 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.40126 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.52568 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31445 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.49808 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35190 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.50739 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33151 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.57995 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.29594 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.54091 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.30211 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.55900 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.29594 * CGRectGetHeight(frame))];
    [bezier4Path closePath];
    [bezier4Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.57862 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31078 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.53620 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32666 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.56291 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31104 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.54876 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31633 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.51275 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37916 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.52105 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33856 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.51323 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35606 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.53342 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42996 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.51323 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.40025 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.52012 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41718 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.57608 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44689 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.54437 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44124 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.55860 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44689 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.62298 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42983 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.59477 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44689 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.61040 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44120 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.64328 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38126 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.63554 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41845 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.64231 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.40226 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.62165 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32823 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.64272 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35903 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.63550 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34136 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.57862 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31078 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.61004 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31633 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.59570 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31051 * CGRectGetHeight(frame))];
    [bezier4Path closePath];
    [bezier4Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.53529 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36380 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.54411 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36807 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.53871 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36380 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.54165 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36523 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.54780 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37864 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.54657 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37091 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.54780 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37444 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.54411 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38966 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.54780 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38310 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.54657 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38677 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.53505 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39399 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.54165 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39255 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.53863 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39399 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.52604 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38979 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.53146 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39399 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.52846 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39259 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.52242 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37877 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.52363 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38699 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.52242 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38332 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.52665 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36748 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.52242 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37413 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.52383 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37037 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.53529 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36380 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.52898 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36503 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.53186 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36380 * CGRectGetHeight(frame))];
    [bezier4Path closePath];
    [bezier4Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.61983 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36420 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.62865 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36846 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.62322 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36420 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.62616 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36562 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.63240 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37903 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.63115 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37131 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.63240 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37483 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.62865 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38992 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.63240 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38341 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.63115 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38704 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.61953 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39426 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.62616 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39281 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.62311 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39426 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.61053 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39012 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.61594 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39426 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.61294 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39288 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.60690 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37916 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.60811 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38736 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.60690 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38371 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.61113 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36800 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.60690 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37452 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.60831 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37081 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.61983 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36420 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.61355 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36547 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.61645 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36420 * CGRectGetHeight(frame))];
    [bezier4Path closePath];
    bezier4Path.miterLimit = 4;
    
    [color22 setFill];
    [bezier4Path fill];
    
    
    //// Bezier 5 Drawing
    UIBezierPath* bezier5Path = UIBezierPath.bezierPath;
    [bezier5Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.69211 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45463 * CGRectGetHeight(frame))];
    [bezier5Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.69211 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.30238 * CGRectGetHeight(frame))];
    [bezier5Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.81804 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.30238 * CGRectGetHeight(frame))];
    [bezier5Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.81817 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41132 * CGRectGetHeight(frame))];
    [bezier5Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.74674 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41132 * CGRectGetHeight(frame))];
    [bezier5Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.74650 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36695 * CGRectGetHeight(frame))];
    [bezier5Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.75943 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36695 * CGRectGetHeight(frame))];
    [bezier5Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.75943 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39741 * CGRectGetHeight(frame))];
    [bezier5Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.80390 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39741 * CGRectGetHeight(frame))];
    [bezier5Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.80390 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31904 * CGRectGetHeight(frame))];
    [bezier5Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.70709 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31904 * CGRectGetHeight(frame))];
    [bezier5Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.70709 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45280 * CGRectGetHeight(frame))];
    [bezier5Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.81720 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45280 * CGRectGetHeight(frame))];
    [bezier5Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.81720 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46868 * CGRectGetHeight(frame))];
    [bezier5Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.69211 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46868 * CGRectGetHeight(frame))];
    [bezier5Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.69211 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45463 * CGRectGetHeight(frame))];
    [bezier5Path closePath];
    [bezier5Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.76039 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35422 * CGRectGetHeight(frame))];
    [bezier5Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.76462 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36538 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.76321 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35711 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.76462 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36083 * CGRectGetHeight(frame))];
    [bezier5Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.76106 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37634 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.76462 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36984 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.76343 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37350 * CGRectGetHeight(frame))];
    [bezier5Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.75242 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38060 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.75868 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37918 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.75580 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38060 * CGRectGetHeight(frame))];
    [bezier5Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.74365 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37621 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.74895 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38060 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.74603 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37914 * CGRectGetHeight(frame))];
    [bezier5Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.74009 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36538 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.74128 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37328 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.74009 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36967 * CGRectGetHeight(frame))];
    [bezier5Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.74365 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35449 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.74009 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36100 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.74128 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35737 * CGRectGetHeight(frame))];
    [bezier5Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.75218 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35015 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.74603 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35160 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.74887 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35015 * CGRectGetHeight(frame))];
    [bezier5Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.76039 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35422 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.75540 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35015 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.75814 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35151 * CGRectGetHeight(frame))];
    [bezier5Path closePath];
    bezier5Path.miterLimit = 4;
    
    [color22 setFill];
    [bezier5Path fill];

}


@end
